services:
  nginx-proxy:
    restart: always
    image: jwilder/nginx-proxy:alpine
    container_name: nginx-proxy
    privileged: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "/etc/nginx-proxy/certs:/etc/nginx/certs:ro"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"

  nginx-letsencrypt:
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    depends_on:
      - nginx-proxy
    volumes_from:
      - nginx-proxy
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/etc/nginx-proxy/certs:/etc/nginx/certs:rw"
    environment:
     - NGINX_PROXY_CONTAINER=nginx-proxy

  sttdb-client:
    image: sttdb/sttdb-client
    container_name: sttdb-client
    environment:
      - VIRTUAL_HOST=sttdb.udl.cat
      - LETSENCRYPT_HOST=sttdb.udl.cat
      - LETSENCRYPT_EMAIL=mariva1995@gmail.com
