version: '2'
services:
  sttdb-client:
    image: sttdb/sttdb-client
    container_name: sttdb-client
    ports:
      - "80:80"
    # environment:
    #   - VIRTUAL_HOST=sttdb.dev.rhizomik.net
    #   - LETSENCRYPT_HOST=sttdb.dev.rhizomik.net
    #   - LETSENCRYPT_EMAIL=contact@email.example
    # network_mode: "bridge"
